### ISSUE TITLE
GlobalContentArea missing ?

### ISSUE THREAD

**Issue by heikobarthel** [diva-e/firstspirit-mocks#1]
Hi,
is it possible to mock the GlobalContentArea so that
  GlobalStoreRoot.getGlobalContentArea()
works?
Cheers, Heiko

**Comment by chrisstornowski** [comment]
I can easily mock this interface and give it the possibility to create a GCAPage and GCAFolder and setting and getting a name.
I can do it at this wednesday.

**Comment by chrisstornowski** [comment]
I create a possibility for mocking GlobalStoreRoot.getGlobalContentArea().
If you need for creating mocked GCAPage and GCAFolders you can ask me in another ticket. I need more time for doing it.

**Comment by heikobarthel** [comment]
Thanks so far
